name: my_app
description: wishlist
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  logging: ^1.2.0
  json_annotation: ^4.7.0
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  retrofit_generator: ^8.0.5
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  json_serializable: ^6.5.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator